### ISSUE TITLE
If leave and return to arduino exten. get Native Library already loaded error 

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/Arduino-Extension#8]
This is a regression from 6.2.2 caused by the  deprecation of the `Object` method `finalize` as of Java 9.
This was not caught by the compiler because the `finalize` method is obtained by reflection.

One way to reproduce:

1. Open Models Library *Arduino Example*
2. Click setup [Do not need to have an arduino board attached, just click OK in the dialog that says "No available arduino ports were found."]
3. Re-Open *Arduino Example*

Error message will appear

> java.lang.UnsatisfiedLinkError: Native Library /Users/aab1638/.jssc/mac_os_x/libjSSC-2.6_x86_64.jnilib already loaded in another classloader
>  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
>  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
>  at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
>  at java.base/java.lang.Runtime.load0(Unknown Source)
>  at java.base/java.lang.System.load(Unknown Source)
>  at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:172)
>  at jssc.SerialPortList.<clinit>(SerialPortList.java:43)
>  at arduino.ArduinoExtension$Ports.report(ArduinoExtension.java:112)
>  at org.nlogo.prim._externreport.report(_externreport.java:31)
>  at org.nlogo.prim._asm_proceduresetup_setprocedurevariable_6.perform()
>  at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
>  at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
>  at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
>  at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
>  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
>  at scala.util.control.Exception$Catch.apply(Exception.scala:228)
>  at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
>  at org.nlogo.job.JobThread.run(JobThread.scala:66)
> 
> NetLogo 6.3.0
> main: org.nlogo.app.AppFrame
> thread: AWT-EventQueue-0
> OpenJDK 64-Bit Server VM 17.0.4 (BellSoft; 17.0.4+8-LTS)
> operating system: Mac OS X 10.14.6 (x86_64 processor)
> Scala version 2.12.16
> JOGL: (3D View not initialized)
> OpenGL Graphics: (3D View not initialized)
> model: Arduino Example
> 
> 02:15:18.265 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 02:15:18.265 OutputEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 02:15:18.264 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
> 02:15:18.192 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 02:15:18.144 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
> 02:15:17.986 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 02:15:17.782 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 02:15:17.580 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 02:15:17.379 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 02:15:17.179 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by brandesNW** [comment]
This is the problematic code


./extensions/arduino/src/main/java/ArduinoExtension.java


```
    //now unload the native library, so that if we're loading the extension
    //again on the same NetLogo run, it doesn't cause us troubles.
    try
    {
      ClassLoader classLoader = this.getClass().getClassLoader() ;
      java.lang.reflect.Field field = ClassLoader.class.getDeclaredField( "nativeLibraries" ) ;
      field.setAccessible(true);
      @SuppressWarnings("unchecked")
      Vector<Object> libs = (Vector<Object>) (field.get(classLoader)) ;
      for ( Object o : libs )
      {
        java.lang.reflect.Method finalize = o.getClass().getDeclaredMethod( "finalize" , new Class<?>[0] ) ;
        finalize.setAccessible( true ) ;
        finalize.invoke( o , new Object[0] ) ;
      }
    }
    catch( Exception e )
    {
      System.err.println( e.getMessage() ) ;
    }
  }
```

I have not been able to find on line a reliable way to unload a library 
The documentation on how to replace finalize has not been helpful either.


[Deprecate Finalization for Removal](https://openjdk.org/jeps/421)

[Java 21 finalize](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Object.html#finalize())

**Comment by brandesNW** [comment]
The workaround is for users who have already opened a model that uses the arduino extension to quit NetLogo if they need to again open a model that uses the arduino extension.
